![IFMG](https://storage.googleapis.com/ifmg/IFMG.png)

---
# Pesquisa Operacional - Trabalho Simplex (Prova 02)


### **Professor: Felipe Reis**

#### **Data: 15-11-2021**

---

In [1]:
import numpy as np
import solver as simplex

In [2]:
#comandos para atualizar automaticamente a função solver
#evita obrigatoriedade de importar arquivo novamente (Jupyter / Colab)
%load_ext autoreload
%autoreload 2

## Requisitos Obrigatórios

O Solver Simplex deverá ser implementado **obrigatoriamente** no arquivo `solver.py`

A entrega não deve ser feita, sob nenhuma hipótese, em arquivos Jupyter / Colab.

O presente arquivo, `simplex.ipynb`, corresponde a apenas uma referência para auxiliar no processo de desenvolvimento do algoritmo.

---
## Método Solver

O método `Solver` deve ser implementado seguindo a estrutura indicada no arquivo `solver.py`, conforme estrutura abaixo.

```
def solver(objet, f_obj, restr_A, restr_op, restr_b, verbose=False):
    """
    Função para solução de problemas de programação linear
    Deve ser implementada para solução de PPL usando métodos Simplex e Simplex Duas Fases.
    Parâmetros:
    : param objet:    string, contendo indicação de 'MA' (para maximização) ou 'MI' (para minimização)
    : param f_obj:    np.array float, contendo a função objetivo
    : param restr_A:  np.array float, contendo a matriz A das restrições
    : param restr_op: np.array string, contendo o vetor de operadores das restrições
    : param restr_b:  np.array float, contendo o vetor b das restrições
    : param verbose:  booleano opcional para impressão de valores intermediários (não obrigatório)
    : return:         np.array contendo os valores das variáveis (não retornar valor da função objetivo)
    """
```

Todos os parâmetros recebidos pelo método deverão ser arrays Numpy (`np.array`).

Caso o parâmetros não seja do tipo especificado, o método retornará mensagem de erro.

Referências: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

#### Exemplo 1 - Parâmetros Adequados

In [3]:
simplex.solver(objet    = 'MA',
               f_obj    = np.array([[3., 2.]]), 
               restr_A  = np.array([[1., 1.], [5., 2.]]), 
               restr_op = np.array([['<='], ['<=']]), 
               restr_b  = np.array([[6.], [20.]]), 
               verbose  = True)

Solver Simplex IFMG


#### Exemplo 2 - Parâmetros Inadequados

In [4]:
simplex.solver(objet    = 'MA',
               f_obj    = [3., 2.],  #array comum = erro
               restr_A  = np.array([[1., 1.], [5., 2.]]), 
               restr_op = np.array([['<='], ['<=']]), 
               restr_b  = np.array([[6.], [20.]]), 
               verbose  = True)

TypeError: Parâmetro "f_obj" diferente do especificado.

---
## Arquivo de Entrada

O arquivo de entrada contém os problemas de programação linear.

Cada linha do arquivo contém um problema. As linhas iniciadas com o caractere `'#'` correspondem a comentários e devem ser ignoradas.

As linhas possuem a seguinte estrutura:

* Função Objetivo
 * Indicador `MA` ou `MI`, para maximização e minimização, respectivamente, seguido de array
 * Array contém o coeficientes da função objetivo


* Função Objetivo
 * Array correspondente à função objetivo
 
 
* Restrições (RE)
 * Indicador de restrições (RE) seguido de arrays
 * Arrays (1 ou múltiplos, separados por `,`) contendo coeficientes das restrições e operadores
 * Dentro dos arrays, os valores estão separados por espaço simples
 * Operadores utilizam sempre dois caracteres: `==`, `<=` ou `>=`
 * Não há espaçamento entre a sigla `RE` e o primeiro array 
 
 
* Solução Função Objetivo (SF)
 * Indicador de solução da função objetivo (SF) seguido de array
 * Array contém o resultado da função objetivo
 * *Deve ser utilizado somente para simples conferência. Não deve ser passado como parâmetro para a função Solver.*
 
 
* Solução das Variáveis (SV)
 * Indicador de solução das restrições (SV) seguido de array
 * Array contém os valores das variáveis
 * *Deve ser utilizado somente para simples conferência. Não deve ser passado como parâmetro para a função Solver.*


#### Informações Adicionais

1. O código deve ser genérico, não devendo funcionar apenas para os problemas existentes no arquivo exemplo.

2. Será utilizado um arquivo extra, com mais problemas, que devem ser solucionados pelo algoritmo.

3. Todos os problemas serão factíveis. Não se preocupar com problemas não factíveis.

4. Informações de solução da Função Objetivo e Variáveis não devem ser passadas como parâmetros, sob nenhuma hipótese, para a função *solver*.

#### Arquivo de Testes

O arquivo de testes pode ser visualizado com o código abaixo.

In [18]:
f = open("problemas.txt","r")
lines = f.readlines()

for l in lines:
    if(l[0] != '#'):     #ignorar linhas iniciadas com o caractere '#'
        print(l, end='')

MA[3 2] RE[1 1 <= 6], [5 2 <= 20] SF[14.67] SV[2.67 3.33]
MI[4 -2] RE[2 1 <= 10], [1 -1 <= 8] SF[-20] SV[10 18]
MA[5 4] RE[6 4 <= 24], [1 2 <= 6], [-1 1 <= 1], [0 1 <=2] SF[21] SV[3 1.5]
MA[1000 1800] RE[20 30 <= 1200], [1 0 <= 40], [0 1 <= 30] SF[69000] SV[15 30]
MA[80 60] RE[4 6 <= 24], [4 2 <= 16], [0 1 <= 3] SF[360] SV[3 2]
MA[600 800 900 500] RE[1 1 1 1 <= 400], [1000 1200 1200 1500 <= 500000], [20 30 25 28 <= 10000] SF[360000] SV[0 0 400 0]
MI[3 2.5] RE[4 8 >= 32], [6 6 >= 36] SF[15] SV[0 6]
MA[9 8] RE[4 2 <= 16], [1 1 <= 5], [1 0 >= 1], [0 1 <= 3] SF[43] SV[3 2]
MA[5 8] RE[2 1 <= 5], [-1 2 >= 3], [1 0 <= 1], [0 1 >= 1] SF[40] SV[0 5]
MA[12 20] RE[0 1 >= 1], [3 2 >= 6], [1 1 <= 5], [0 1 <= 3] SF[84] SV[2 3]
MA[8 10] RE[2 2 <= 6], [4 1 >= 4], [3 1 <= 5], [0 1 >= 1] SF[16] SV[0.75 1]
MI[20 25 25 25] RE[1 0 1 == 500], [0 1 0 1 == 1000], [1 0 0 0 == 400], [0 1 0 0 == 800], [0 0 1 1 == 600] SF[35500] SV[400 800 100 200]

#### Transformação em PPL

A primeira linha do arquivo pode ser traduzida em um Problema de Programação Linear.

##### Linha Exemplo

`MA[3 2] RE[1 1 <= 6], [5 2 <= 20] SF[14.67] SV[2.67 3.33]`

##### Problema Programação Linear

$ max~z = 3 x_1 + 2 x_2 $

$ suj. a $

$ \qquad 1 x_1 + 1 x_2 \le 6 $

$ \qquad 5 x_1 + 2 x_2 \le 20 $

$ \qquad x_1, x_2 \ge 0 $

##### Representação em Matrizes e Vetores

A linha pode ser transformadas nos vetores abaixo:

In [19]:
objet    = 'MA'
f_obj    = np.array([[3., 2.]])
restr_A  = np.array([[1., 1.], [5., 2.]])
restr_op = np.array([['<=', '<=']])  #array em formato linha (para formato coluna, utilize restr_op.transpose())
restr_b  = np.array([[6., 20.]])     #array em formato linha (para formato coluna, utilize restr_b.transpose())

print('Objetivo:', 'MAXIMIZAR' if objet == 'MA' else 'MINIMIZAR', end='\n\n')
print('Função objetivo: \n', f_obj, end='\n\n')
print('Matriz Restrições A: \n', restr_A, end='\n\n')
print('Matriz Restrições op: \n', restr_op, end='\n\n')
print('Matriz Restrições b: \n', restr_b, end='\n\n')
print()

Objetivo: MAXIMIZAR

Função objetivo: 
 [[3. 2.]]

Matriz Restrições A: 
 [[1. 1.]
 [5. 2.]]

Matriz Restrições op: 
 [['<=' '<=']]

Matriz Restrições b: 
 [[ 6. 20.]]




##### Processamento da linha com Solver

A linha pode ser processada pelo Solver com auxílio do código abaixo.

In [21]:
simplex.solver(objet    = objet,
               f_obj    = f_obj,
               restr_A  = restr_A,
               restr_op = restr_op,
               restr_b  = restr_b,
               verbose  = True)

Solver Simplex IFMG


---
## Simplex Tableau

Para solução dos problemas, devem ser criada uma matriz correspondente ao Simplex Tableau.

O Tableau deve, **obrigatoriamente**, seguir o modelo adotado na disciplina e disponível nos slides de aula.

O parâmetro `verbose` deve permitir a impressão do Tableau, passo a passo.

#### Adição de colunas em uma matriz

O link abaixo exemplifica o mecanismo para adição de colunas em uma array Numpy.

https://stackoverflow.com/questions/8486294/how-to-add-an-extra-column-to-a-numpy-array

In [36]:
len_A = len(restr_A[0]) #número de colunas da restrição A

print('Matriz A')
print(restr_A)
print()

print('Matriz A + 1 coluna')
exp_A = np.c_[restr_A, np.zeros(len_A)] #1 coluna
print(exp_A)
print()

print('Matriz A + 2 colunas')
exp_A = np.c_[restr_A, np.zeros(len_A), np.zeros(len_A)] #1 coluna
print(exp_A)

Matriz A
[[1. 1.]
 [5. 2.]]

Matriz A + 1 coluna
[[1. 1. 0.]
 [5. 2. 0.]]

Matriz A + 2 colunas
[[1. 1. 0. 0.]
 [5. 2. 0. 0.]]


### Exemplo Simplex Tableau

O PPL usado como exemplo pode ser transformado em um Tableau Simplex.

In [22]:
tableau = np.array([[0. , -3., -2., 0., 0.],
                    [6. ,  1.,  1., 1., 0.],
                    [20.,  5.,  2., 0., 1.]]
                  )

print('Tableau:')
print(tableau)

print()
print('Base:', [0., 0., 1., 1.]) #variáveis de folga x3 e x4 constituem a base

Tableau:
[[ 0. -3. -2.  0.  0.]
 [ 6.  1.  1.  1.  0.]
 [20.  5.  2.  0.  1.]]

Base: [0.0, 0.0, 1.0, 1.0]


##### Iteração 1

Na primeira iteração (slides 39-54 do material de aula), define-se que $x_1$, entrará na base no local de $x_4$ (linha $L_2$).

A operação da primeira iteração pode ser especificada no código abaixo.

In [23]:
tableau = np.array([[0., -3., -2., 0., 0.],[6., 1., 1., 1., 0.], [20., 5., 2., 0., 1.]])

#definição das linhas
L0 = tableau[0,:]
L1 = tableau[1,:]
L2 = tableau[2,:]

print(L0)
print(L1)
print(L2)
print()

#gauss-jordan linha 2
L2 = tableau[2,:] / 5
print('Linha L2:', L2)

#gauss-jordan linha 0
L0 = L0 + 3*L2
print('Linha L0:', L0)

#gauss-jordan linha 1
L1 = L1 - 1*L2
print('Linha L1:', L1)

#atualização do Tableau (1a iteração)
tableau[0, :] = L0
tableau[1, :] = L1
tableau[2, :] = L2
print()
print('Tableau:\n', tableau)

[ 0. -3. -2.  0.  0.]
[6. 1. 1. 1. 0.]
[20.  5.  2.  0.  1.]

Linha L2: [4.  1.  0.4 0.  0.2]
Linha L0: [12.   0.  -0.8  0.   0.6]
Linha L1: [ 2.   0.   0.6  1.  -0.2]

Tableau:
 [[12.   0.  -0.8  0.   0.6]
 [ 2.   0.   0.6  1.  -0.2]
 [ 4.   1.   0.4  0.   0.2]]


---
## Funções Úteis

As funções abaixo podem auxiliar na transformação das informações existentes nos arquivos em matrizes.

In [24]:
txt = 'MA[3 2] RE[1 1 <= 6], [5 2 <= 20] SF[14.67] SV[2.67 3.33]'

#índices (posições) de expressões em strings
ind_fo = txt.index('R')
ind_re = txt.index('SF')
ind_sf = txt.index('SV')

#substring
fo = txt[0 : ind_fo-1]
re = txt[ind_fo : ind_re]
sf = txt[ind_re : ind_sf]
sv = txt[ind_sf :]

#impressão de dados
print(fo)
print(re)
print(sf)
print(sv)

#conversão de restrições em matrizes de string
print()
re_split = re[2:].split(',')
for i in re_split:
    print(i.split())

MA[3 2]
RE[1 1 <= 6], [5 2 <= 20] 
SF[14.67] 
SV[2.67 3.33]

['[1', '1', '<=', '6]']
['[5', '2', '<=', '20]']
